# Generated by Django 5.2.7 on 2025-11-04 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the person or organization",
                        max_length=200,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("galerie", "Galerie"),
                            ("musee", "Musée"),
                            ("collectionneur", "Collectionneur"),
                            ("expert", "Expert"),
                            ("restaurateur", "Restaurateur"),
                            ("transporteur", "Transporteur"),
                            ("assureur", "Assureur"),
                            ("autre", "Autre"),
                        ],
                        help_text="Type of professional contact",
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Complete mailing address",
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary phone number",
                        max_length=20,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary email address",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Website or social media URL",
                        verbose_name="Site web",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes, specialties, or relationship details",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this contact was added"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this contact was last updated"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this contact",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["name"],
            },
        ),
    ]
