# Generated by Django 5.2.7 on 2025-11-04 18:15

import uuid

import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Type d'art")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Type d'art",
                'verbose_name_plural': "Types d'art",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Support')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Support',
                'verbose_name_plural': 'Supports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Technique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Technique',
                'verbose_name_plural': 'Techniques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Année de naissance')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Année de décès')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationalité')),
                ('biography', models.TextField(blank=True, verbose_name='Biographie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artiste',
                'verbose_name_plural': 'Artistes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Titre')),
                ('creation_year', models.IntegerField(blank=True, null=True, verbose_name='Année de création')),
                ('origin_country', models.CharField(blank=True, max_length=100, verbose_name="Pays d'origine")),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hauteur (cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largeur (cm)')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Profondeur (cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Poids (kg)')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name="Date d'acquisition")),
                ('acquisition_place', models.CharField(blank=True, max_length=200, verbose_name="Lieu d'acquisition")),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix (€)')),
                ('provenance', models.TextField(blank=True, verbose_name='Provenance')),
                ('is_framed', models.BooleanField(default=False, verbose_name='Est encadrée')),
                ('is_borrowed', models.BooleanField(default=False, verbose_name='Est empruntée')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Est signée')),
                ('is_acquired', models.BooleanField(default=True, verbose_name='Est acquise')),
                ('current_location', models.CharField(choices=[('domicile', 'Domicile'), ('stockage', 'Stockage'), ('pretee', 'Prêtée'), ('restauration', 'En restauration'), ('encadrement', 'En encadrement'), ('restitution', 'En restitution'), ('vente', 'En vente'), ('vendue', 'Vendue'), ('perdue', 'Perdue'), ('volée', 'Volée'), ('volée', 'Volée'), ('autre', 'Autre')], default='domicile', max_length=50, verbose_name='Localisation actuelle')),
                ('owners', models.CharField(blank=True, max_length=500, verbose_name='Propriétaire(s)')),
                ('contextual_references', models.TextField(blank=True, verbose_name='Références contextuelles')),
                ('notes', models.TextField(blank=True, verbose_name='Notes libres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_exhibited', models.DateField(blank=True, null=True, verbose_name='Dernière exposition')),
                ('art_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.arttype', verbose_name="Type d'art")),
                ('artists', models.ManyToManyField(blank=True, to='artworks.artist', verbose_name='Artiste(s)')),
                ('parent_artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.artwork', verbose_name='Œuvre parente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Œuvre d'art",
                'verbose_name_plural': "Œuvres d'art",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Titre')),
                ('file', models.FileField(upload_to='artwork_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'odt', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'jpg', 'jpeg', 'png', 'tif', 'tiff', 'zip'])], verbose_name='Fichier')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Notes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='artworks.artwork')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='artworks/')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Légende')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='artworks.artwork')),
            ],
            options={
                'verbose_name': "Photo d'œuvre",
                'verbose_name_plural': "Photos d'œuvres",
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la collection')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='collections',
            field=models.ManyToManyField(blank=True, to='artworks.collection', verbose_name='Collection(s)'),
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'exposition")),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exposition',
                'verbose_name_plural': 'Expositions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='exhibitions',
            field=models.ManyToManyField(blank=True, to='artworks.exhibition', verbose_name='Exposition(s)'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.support', verbose_name='Support'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.technique', verbose_name='Technique'),
        ),
        migrations.CreateModel(
            name='UUIDTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks_%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='artworks.UUIDTaggedItem', to='taggit.Tag', verbose_name='Mots-clés'),
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Général', max_length=300, verbose_name='Titre')),
                ('artist_name', models.CharField(blank=True, max_length=200, verbose_name='Artiste')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix estimé (€)')),
                ('priority', models.IntegerField(choices=[(1, 'Haute'), (2, 'Moyenne'), (3, 'Basse')], default=3, verbose_name='Priorité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('source_url', models.URLField(blank=True, verbose_name='URL source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Œuvre convoitée',
                'verbose_name_plural': 'Œuvres convoitées',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
